// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createAgent, deleteAgent, getAgent, listAgents, type Options, updateAgent } from '../sdk.gen';
import type { CreateAgentData, CreateAgentResponse, DeleteAgentData, DeleteAgentError, DeleteAgentResponse, GetAgentData, GetAgentError, GetAgentResponse, ListAgentsData, ListAgentsResponse, UpdateAgentData, UpdateAgentError, UpdateAgentResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listAgentsQueryKey = (options?: Options<ListAgentsData>) => createQueryKey('listAgents', options);

/**
 * List agents
 */
export const listAgentsOptions = (options?: Options<ListAgentsData>) => queryOptions<ListAgentsResponse, DefaultError, ListAgentsResponse, ReturnType<typeof listAgentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listAgents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listAgentsQueryKey(options)
});

/**
 * Create an agent
 */
export const createAgentMutation = (options?: Partial<Options<CreateAgentData>>): UseMutationOptions<CreateAgentResponse, DefaultError, Options<CreateAgentData>> => {
    const mutationOptions: UseMutationOptions<CreateAgentResponse, DefaultError, Options<CreateAgentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createAgent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete an agent
 */
export const deleteAgentMutation = (options?: Partial<Options<DeleteAgentData>>): UseMutationOptions<DeleteAgentResponse, DeleteAgentError, Options<DeleteAgentData>> => {
    const mutationOptions: UseMutationOptions<DeleteAgentResponse, DeleteAgentError, Options<DeleteAgentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteAgent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAgentQueryKey = (options: Options<GetAgentData>) => createQueryKey('getAgent', options);

/**
 * Get an agent by id
 */
export const getAgentOptions = (options: Options<GetAgentData>) => queryOptions<GetAgentResponse, GetAgentError, GetAgentResponse, ReturnType<typeof getAgentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAgent({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAgentQueryKey(options)
});

/**
 * Update an agent
 */
export const updateAgentMutation = (options?: Partial<Options<UpdateAgentData>>): UseMutationOptions<UpdateAgentResponse, UpdateAgentError, Options<UpdateAgentData>> => {
    const mutationOptions: UseMutationOptions<UpdateAgentResponse, UpdateAgentError, Options<UpdateAgentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateAgent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
