// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createAgent, createSpeechClientSecret, createSpeechSession, deleteAgent, deleteConciergeDoctorSession, deleteSpeechSession, ensureConciergeDoctorAgent, getAgent, getConciergeDoctorSession, getSpeechSession, listAgents, listConciergeDoctorSessions, listSpeechSessions, mockConciergePharmacyRequest, mockConciergeScheduleFollowUp, type Options, startConciergeDoctorSession, updateAgent, updateConciergeDoctorSession, updateSpeechSession } from '../sdk.gen';
import type { CreateAgentData, CreateAgentResponse, CreateSpeechClientSecretData, CreateSpeechClientSecretError, CreateSpeechClientSecretResponse, CreateSpeechSessionData, CreateSpeechSessionResponse, DeleteAgentData, DeleteAgentError, DeleteAgentResponse, DeleteConciergeDoctorSessionData, DeleteConciergeDoctorSessionError, DeleteConciergeDoctorSessionResponse, DeleteSpeechSessionData, DeleteSpeechSessionError, DeleteSpeechSessionResponse, EnsureConciergeDoctorAgentData, EnsureConciergeDoctorAgentError, EnsureConciergeDoctorAgentResponse, GetAgentData, GetAgentError, GetAgentResponse, GetConciergeDoctorSessionData, GetConciergeDoctorSessionError, GetConciergeDoctorSessionResponse, GetSpeechSessionData, GetSpeechSessionError, GetSpeechSessionResponse, ListAgentsData, ListAgentsResponse, ListConciergeDoctorSessionsData, ListConciergeDoctorSessionsResponse, ListSpeechSessionsData, ListSpeechSessionsResponse, MockConciergePharmacyRequestData, MockConciergePharmacyRequestResponse, MockConciergeScheduleFollowUpData, MockConciergeScheduleFollowUpResponse, StartConciergeDoctorSessionData, StartConciergeDoctorSessionError, StartConciergeDoctorSessionResponse, UpdateAgentData, UpdateAgentError, UpdateAgentResponse, UpdateConciergeDoctorSessionData, UpdateConciergeDoctorSessionError, UpdateConciergeDoctorSessionResponse, UpdateSpeechSessionData, UpdateSpeechSessionError, UpdateSpeechSessionResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listAgentsQueryKey = (options?: Options<ListAgentsData>) => createQueryKey('listAgents', options);

/**
 * List agents
 */
export const listAgentsOptions = (options?: Options<ListAgentsData>) => queryOptions<ListAgentsResponse, DefaultError, ListAgentsResponse, ReturnType<typeof listAgentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listAgents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listAgentsQueryKey(options)
});

/**
 * Create an agent
 */
export const createAgentMutation = (options?: Partial<Options<CreateAgentData>>): UseMutationOptions<CreateAgentResponse, DefaultError, Options<CreateAgentData>> => {
    const mutationOptions: UseMutationOptions<CreateAgentResponse, DefaultError, Options<CreateAgentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createAgent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete an agent
 */
export const deleteAgentMutation = (options?: Partial<Options<DeleteAgentData>>): UseMutationOptions<DeleteAgentResponse, DeleteAgentError, Options<DeleteAgentData>> => {
    const mutationOptions: UseMutationOptions<DeleteAgentResponse, DeleteAgentError, Options<DeleteAgentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteAgent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAgentQueryKey = (options: Options<GetAgentData>) => createQueryKey('getAgent', options);

/**
 * Get an agent by id
 */
export const getAgentOptions = (options: Options<GetAgentData>) => queryOptions<GetAgentResponse, GetAgentError, GetAgentResponse, ReturnType<typeof getAgentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAgent({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAgentQueryKey(options)
});

/**
 * Update an agent
 */
export const updateAgentMutation = (options?: Partial<Options<UpdateAgentData>>): UseMutationOptions<UpdateAgentResponse, UpdateAgentError, Options<UpdateAgentData>> => {
    const mutationOptions: UseMutationOptions<UpdateAgentResponse, UpdateAgentError, Options<UpdateAgentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateAgent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listSpeechSessionsQueryKey = (options?: Options<ListSpeechSessionsData>) => createQueryKey('listSpeechSessions', options);

/**
 * List speech sessions
 */
export const listSpeechSessionsOptions = (options?: Options<ListSpeechSessionsData>) => queryOptions<ListSpeechSessionsResponse, DefaultError, ListSpeechSessionsResponse, ReturnType<typeof listSpeechSessionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listSpeechSessions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listSpeechSessionsQueryKey(options)
});

/**
 * Create a speech session
 */
export const createSpeechSessionMutation = (options?: Partial<Options<CreateSpeechSessionData>>): UseMutationOptions<CreateSpeechSessionResponse, DefaultError, Options<CreateSpeechSessionData>> => {
    const mutationOptions: UseMutationOptions<CreateSpeechSessionResponse, DefaultError, Options<CreateSpeechSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createSpeechSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create an OpenAI Realtime ephemeral client secret
 */
export const createSpeechClientSecretMutation = (options?: Partial<Options<CreateSpeechClientSecretData>>): UseMutationOptions<CreateSpeechClientSecretResponse, CreateSpeechClientSecretError, Options<CreateSpeechClientSecretData>> => {
    const mutationOptions: UseMutationOptions<CreateSpeechClientSecretResponse, CreateSpeechClientSecretError, Options<CreateSpeechClientSecretData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createSpeechClientSecret({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a speech session
 */
export const deleteSpeechSessionMutation = (options?: Partial<Options<DeleteSpeechSessionData>>): UseMutationOptions<DeleteSpeechSessionResponse, DeleteSpeechSessionError, Options<DeleteSpeechSessionData>> => {
    const mutationOptions: UseMutationOptions<DeleteSpeechSessionResponse, DeleteSpeechSessionError, Options<DeleteSpeechSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteSpeechSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSpeechSessionQueryKey = (options: Options<GetSpeechSessionData>) => createQueryKey('getSpeechSession', options);

/**
 * Get a speech session by id
 */
export const getSpeechSessionOptions = (options: Options<GetSpeechSessionData>) => queryOptions<GetSpeechSessionResponse, GetSpeechSessionError, GetSpeechSessionResponse, ReturnType<typeof getSpeechSessionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSpeechSession({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSpeechSessionQueryKey(options)
});

/**
 * Update a speech session
 */
export const updateSpeechSessionMutation = (options?: Partial<Options<UpdateSpeechSessionData>>): UseMutationOptions<UpdateSpeechSessionResponse, UpdateSpeechSessionError, Options<UpdateSpeechSessionData>> => {
    const mutationOptions: UseMutationOptions<UpdateSpeechSessionResponse, UpdateSpeechSessionError, Options<UpdateSpeechSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateSpeechSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Ensure the ElevenLabs concierge doctor agent exists
 */
export const ensureConciergeDoctorAgentMutation = (options?: Partial<Options<EnsureConciergeDoctorAgentData>>): UseMutationOptions<EnsureConciergeDoctorAgentResponse, EnsureConciergeDoctorAgentError, Options<EnsureConciergeDoctorAgentData>> => {
    const mutationOptions: UseMutationOptions<EnsureConciergeDoctorAgentResponse, EnsureConciergeDoctorAgentError, Options<EnsureConciergeDoctorAgentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ensureConciergeDoctorAgent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listConciergeDoctorSessionsQueryKey = (options?: Options<ListConciergeDoctorSessionsData>) => createQueryKey('listConciergeDoctorSessions', options);

/**
 * List concierge doctor sessions
 */
export const listConciergeDoctorSessionsOptions = (options?: Options<ListConciergeDoctorSessionsData>) => queryOptions<ListConciergeDoctorSessionsResponse, DefaultError, ListConciergeDoctorSessionsResponse, ReturnType<typeof listConciergeDoctorSessionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listConciergeDoctorSessions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listConciergeDoctorSessionsQueryKey(options)
});

/**
 * Delete a concierge doctor session
 */
export const deleteConciergeDoctorSessionMutation = (options?: Partial<Options<DeleteConciergeDoctorSessionData>>): UseMutationOptions<DeleteConciergeDoctorSessionResponse, DeleteConciergeDoctorSessionError, Options<DeleteConciergeDoctorSessionData>> => {
    const mutationOptions: UseMutationOptions<DeleteConciergeDoctorSessionResponse, DeleteConciergeDoctorSessionError, Options<DeleteConciergeDoctorSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteConciergeDoctorSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getConciergeDoctorSessionQueryKey = (options: Options<GetConciergeDoctorSessionData>) => createQueryKey('getConciergeDoctorSession', options);

/**
 * Get a concierge doctor session
 */
export const getConciergeDoctorSessionOptions = (options: Options<GetConciergeDoctorSessionData>) => queryOptions<GetConciergeDoctorSessionResponse, GetConciergeDoctorSessionError, GetConciergeDoctorSessionResponse, ReturnType<typeof getConciergeDoctorSessionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getConciergeDoctorSession({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getConciergeDoctorSessionQueryKey(options)
});

/**
 * Update a concierge doctor session
 */
export const updateConciergeDoctorSessionMutation = (options?: Partial<Options<UpdateConciergeDoctorSessionData>>): UseMutationOptions<UpdateConciergeDoctorSessionResponse, UpdateConciergeDoctorSessionError, Options<UpdateConciergeDoctorSessionData>> => {
    const mutationOptions: UseMutationOptions<UpdateConciergeDoctorSessionResponse, UpdateConciergeDoctorSessionError, Options<UpdateConciergeDoctorSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateConciergeDoctorSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Start a concierge doctor conversation
 */
export const startConciergeDoctorSessionMutation = (options?: Partial<Options<StartConciergeDoctorSessionData>>): UseMutationOptions<StartConciergeDoctorSessionResponse, StartConciergeDoctorSessionError, Options<StartConciergeDoctorSessionData>> => {
    const mutationOptions: UseMutationOptions<StartConciergeDoctorSessionResponse, StartConciergeDoctorSessionError, Options<StartConciergeDoctorSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await startConciergeDoctorSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Mock retail pharmacy portal action
 */
export const mockConciergePharmacyRequestMutation = (options?: Partial<Options<MockConciergePharmacyRequestData>>): UseMutationOptions<MockConciergePharmacyRequestResponse, DefaultError, Options<MockConciergePharmacyRequestData>> => {
    const mutationOptions: UseMutationOptions<MockConciergePharmacyRequestResponse, DefaultError, Options<MockConciergePharmacyRequestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await mockConciergePharmacyRequest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Mock provider follow-up scheduling
 */
export const mockConciergeScheduleFollowUpMutation = (options?: Partial<Options<MockConciergeScheduleFollowUpData>>): UseMutationOptions<MockConciergeScheduleFollowUpResponse, DefaultError, Options<MockConciergeScheduleFollowUpData>> => {
    const mutationOptions: UseMutationOptions<MockConciergeScheduleFollowUpResponse, DefaultError, Options<MockConciergeScheduleFollowUpData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await mockConciergeScheduleFollowUp({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
