// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateAgentData, CreateAgentResponses, CreateSpeechClientSecretData, CreateSpeechClientSecretErrors, CreateSpeechClientSecretResponses, CreateSpeechSessionData, CreateSpeechSessionResponses, DeleteAgentData, DeleteAgentErrors, DeleteAgentResponses, DeleteConciergeDoctorSessionData, DeleteConciergeDoctorSessionErrors, DeleteConciergeDoctorSessionResponses, DeleteSpeechSessionData, DeleteSpeechSessionErrors, DeleteSpeechSessionResponses, EnsureConciergeDoctorAgentData, EnsureConciergeDoctorAgentErrors, EnsureConciergeDoctorAgentResponses, GetAgentData, GetAgentErrors, GetAgentResponses, GetConciergeDoctorSessionData, GetConciergeDoctorSessionErrors, GetConciergeDoctorSessionResponses, GetSpeechSessionData, GetSpeechSessionErrors, GetSpeechSessionResponses, ListAgentsData, ListAgentsResponses, ListConciergeDoctorSessionsData, ListConciergeDoctorSessionsResponses, ListSpeechSessionsData, ListSpeechSessionsResponses, MockConciergePharmacyRequestData, MockConciergePharmacyRequestResponses, MockConciergeScheduleFollowUpData, MockConciergeScheduleFollowUpResponses, StartConciergeDoctorSessionData, StartConciergeDoctorSessionErrors, StartConciergeDoctorSessionResponses, UpdateAgentData, UpdateAgentErrors, UpdateAgentResponses, UpdateConciergeDoctorSessionData, UpdateConciergeDoctorSessionErrors, UpdateConciergeDoctorSessionResponses, UpdateSpeechSessionData, UpdateSpeechSessionErrors, UpdateSpeechSessionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List agents
 */
export const listAgents = <ThrowOnError extends boolean = false>(options?: Options<ListAgentsData, ThrowOnError>): RequestResult<ListAgentsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListAgentsResponses, unknown, ThrowOnError>({ url: '/agents', ...options });

/**
 * Create an agent
 */
export const createAgent = <ThrowOnError extends boolean = false>(options: Options<CreateAgentData, ThrowOnError>): RequestResult<CreateAgentResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateAgentResponses, unknown, ThrowOnError>({
    url: '/agents',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete an agent
 */
export const deleteAgent = <ThrowOnError extends boolean = false>(options: Options<DeleteAgentData, ThrowOnError>): RequestResult<DeleteAgentResponses, DeleteAgentErrors, ThrowOnError> => (options.client ?? client).delete<DeleteAgentResponses, DeleteAgentErrors, ThrowOnError>({ url: '/agents/{id}', ...options });

/**
 * Get an agent by id
 */
export const getAgent = <ThrowOnError extends boolean = false>(options: Options<GetAgentData, ThrowOnError>): RequestResult<GetAgentResponses, GetAgentErrors, ThrowOnError> => (options.client ?? client).get<GetAgentResponses, GetAgentErrors, ThrowOnError>({ url: '/agents/{id}', ...options });

/**
 * Update an agent
 */
export const updateAgent = <ThrowOnError extends boolean = false>(options: Options<UpdateAgentData, ThrowOnError>): RequestResult<UpdateAgentResponses, UpdateAgentErrors, ThrowOnError> => (options.client ?? client).patch<UpdateAgentResponses, UpdateAgentErrors, ThrowOnError>({
    url: '/agents/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List speech sessions
 */
export const listSpeechSessions = <ThrowOnError extends boolean = false>(options?: Options<ListSpeechSessionsData, ThrowOnError>): RequestResult<ListSpeechSessionsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListSpeechSessionsResponses, unknown, ThrowOnError>({ url: '/speech-sessions', ...options });

/**
 * Create a speech session
 */
export const createSpeechSession = <ThrowOnError extends boolean = false>(options: Options<CreateSpeechSessionData, ThrowOnError>): RequestResult<CreateSpeechSessionResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateSpeechSessionResponses, unknown, ThrowOnError>({
    url: '/speech-sessions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create an OpenAI Realtime ephemeral client secret
 */
export const createSpeechClientSecret = <ThrowOnError extends boolean = false>(options?: Options<CreateSpeechClientSecretData, ThrowOnError>): RequestResult<CreateSpeechClientSecretResponses, CreateSpeechClientSecretErrors, ThrowOnError> => (options?.client ?? client).post<CreateSpeechClientSecretResponses, CreateSpeechClientSecretErrors, ThrowOnError>({
    url: '/speech-sessions/client-secret',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete a speech session
 */
export const deleteSpeechSession = <ThrowOnError extends boolean = false>(options: Options<DeleteSpeechSessionData, ThrowOnError>): RequestResult<DeleteSpeechSessionResponses, DeleteSpeechSessionErrors, ThrowOnError> => (options.client ?? client).delete<DeleteSpeechSessionResponses, DeleteSpeechSessionErrors, ThrowOnError>({ url: '/speech-sessions/{id}', ...options });

/**
 * Get a speech session by id
 */
export const getSpeechSession = <ThrowOnError extends boolean = false>(options: Options<GetSpeechSessionData, ThrowOnError>): RequestResult<GetSpeechSessionResponses, GetSpeechSessionErrors, ThrowOnError> => (options.client ?? client).get<GetSpeechSessionResponses, GetSpeechSessionErrors, ThrowOnError>({ url: '/speech-sessions/{id}', ...options });

/**
 * Update a speech session
 */
export const updateSpeechSession = <ThrowOnError extends boolean = false>(options: Options<UpdateSpeechSessionData, ThrowOnError>): RequestResult<UpdateSpeechSessionResponses, UpdateSpeechSessionErrors, ThrowOnError> => (options.client ?? client).patch<UpdateSpeechSessionResponses, UpdateSpeechSessionErrors, ThrowOnError>({
    url: '/speech-sessions/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Ensure the ElevenLabs concierge doctor agent exists
 */
export const ensureConciergeDoctorAgent = <ThrowOnError extends boolean = false>(options?: Options<EnsureConciergeDoctorAgentData, ThrowOnError>): RequestResult<EnsureConciergeDoctorAgentResponses, EnsureConciergeDoctorAgentErrors, ThrowOnError> => (options?.client ?? client).post<EnsureConciergeDoctorAgentResponses, EnsureConciergeDoctorAgentErrors, ThrowOnError>({
    url: '/concierge-doctor/ensure-agent',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * List concierge doctor sessions
 */
export const listConciergeDoctorSessions = <ThrowOnError extends boolean = false>(options?: Options<ListConciergeDoctorSessionsData, ThrowOnError>): RequestResult<ListConciergeDoctorSessionsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListConciergeDoctorSessionsResponses, unknown, ThrowOnError>({ url: '/concierge-doctor/sessions', ...options });

/**
 * Delete a concierge doctor session
 */
export const deleteConciergeDoctorSession = <ThrowOnError extends boolean = false>(options: Options<DeleteConciergeDoctorSessionData, ThrowOnError>): RequestResult<DeleteConciergeDoctorSessionResponses, DeleteConciergeDoctorSessionErrors, ThrowOnError> => (options.client ?? client).delete<DeleteConciergeDoctorSessionResponses, DeleteConciergeDoctorSessionErrors, ThrowOnError>({ url: '/concierge-doctor/sessions/{id}', ...options });

/**
 * Get a concierge doctor session
 */
export const getConciergeDoctorSession = <ThrowOnError extends boolean = false>(options: Options<GetConciergeDoctorSessionData, ThrowOnError>): RequestResult<GetConciergeDoctorSessionResponses, GetConciergeDoctorSessionErrors, ThrowOnError> => (options.client ?? client).get<GetConciergeDoctorSessionResponses, GetConciergeDoctorSessionErrors, ThrowOnError>({ url: '/concierge-doctor/sessions/{id}', ...options });

/**
 * Update a concierge doctor session
 */
export const updateConciergeDoctorSession = <ThrowOnError extends boolean = false>(options: Options<UpdateConciergeDoctorSessionData, ThrowOnError>): RequestResult<UpdateConciergeDoctorSessionResponses, UpdateConciergeDoctorSessionErrors, ThrowOnError> => (options.client ?? client).patch<UpdateConciergeDoctorSessionResponses, UpdateConciergeDoctorSessionErrors, ThrowOnError>({
    url: '/concierge-doctor/sessions/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Start a concierge doctor conversation
 */
export const startConciergeDoctorSession = <ThrowOnError extends boolean = false>(options?: Options<StartConciergeDoctorSessionData, ThrowOnError>): RequestResult<StartConciergeDoctorSessionResponses, StartConciergeDoctorSessionErrors, ThrowOnError> => (options?.client ?? client).post<StartConciergeDoctorSessionResponses, StartConciergeDoctorSessionErrors, ThrowOnError>({
    url: '/concierge-doctor/sessions/start',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Mock retail pharmacy portal action
 */
export const mockConciergePharmacyRequest = <ThrowOnError extends boolean = false>(options: Options<MockConciergePharmacyRequestData, ThrowOnError>): RequestResult<MockConciergePharmacyRequestResponses, unknown, ThrowOnError> => (options.client ?? client).post<MockConciergePharmacyRequestResponses, unknown, ThrowOnError>({
    url: '/concierge-doctor/mocks/pharmacy',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Mock provider follow-up scheduling
 */
export const mockConciergeScheduleFollowUp = <ThrowOnError extends boolean = false>(options: Options<MockConciergeScheduleFollowUpData, ThrowOnError>): RequestResult<MockConciergeScheduleFollowUpResponses, unknown, ThrowOnError> => (options.client ?? client).post<MockConciergeScheduleFollowUpResponses, unknown, ThrowOnError>({
    url: '/concierge-doctor/mocks/schedule',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
